vich_uploader:
    db_driver: orm
    mappings:
        team_images:
            uri_prefix:         %main.team.uri_prefix%
            upload_destination: %main.team.images_path%
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
